[package]
name = "joyent-rust-utils"
version = "0.1.0"
authors = ["Rui Loura <rui@joyent.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trust-dns-resolver = "0.12.0"
